// ----------------------------------------------------------------
// 🛑 AUTO-GENERATED FILE - DO NOT EDIT!
// Regenerated by: edgespark pull schema --db
//
// To modify your database schema (multiple statements in one command):
//   edgespark db sql "CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT);
//     CREATE TABLE posts (id INTEGER PRIMARY KEY, user_id INTEGER REFERENCES users(id), created_at INTEGER);
//     CREATE INDEX idx_posts_created ON posts(created_at)"
//
// To query your database:
//   edgespark db sql "SELECT * FROM posts; SELECT COUNT(*) FROM users"
// ----------------------------------------------------------------

import { sqliteTable, AnySQLiteColumn, uniqueIndex, text, integer, index } from "drizzle-orm/sqlite-core"
  import { sql } from "drizzle-orm"

export const esSystemAuthUser = sqliteTable("es_system__auth_user", {
	id: text().primaryKey().notNull(),
	name: text().notNull(),
	email: text().notNull(),
	emailVerified: integer("email_verified").default(0).notNull(),
	image: text(),
	createdAt: integer("created_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	updatedAt: integer("updated_at").default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`).notNull(),
	isAnonymous: integer("is_anonymous").default(0),
	internalA: text("__internal_a"),
	banned: integer().default(0),
	banReason: text("ban_reason"),
	banExpires: integer("ban_expires"),
	lastLoginAt: integer("last_login_at"),
},
(table) => [
	uniqueIndex("es_system__auth_user_email_unique").on(table.email),
]);

export const tasks = sqliteTable("tasks", {
	id: integer().primaryKey({ autoIncrement: true }),
	userId: text("user_id").notNull(),
	title: text().notNull(),
	description: text(),
	status: text().default("backlog").notNull(),
	priority: text().default("medium").notNull(),
	dueDate: text("due_date"),
	dueTime: text("due_time"),
	anticipatedMood: text("anticipated_mood"),
	completedMood: text("completed_mood"),
	reflectionNote: text("reflection_note"),
	reflectionPhotoS3Uri: text("reflection_photo_s3_uri"),
	orderIndex: integer("order_index").default(0).notNull(),
	completedAt: integer("completed_at"),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`).notNull(),
},
(table) => [
	index("tasks_due_date_idx").on(table.dueDate),
	index("tasks_user_status_idx").on(table.userId, table.status),
	index("tasks_status_idx").on(table.status),
	index("tasks_user_id_idx").on(table.userId),
]);

export const userPreferences = sqliteTable("user_preferences", {
	userId: text("user_id").primaryKey(),
	emojiSet: text("emoji_set").default("default").notNull(),
	colorPalette: text("color_palette").default("vibrant").notNull(),
	visualizationIntensity: text("visualization_intensity").default("balanced").notNull(),
	createdAt: integer("created_at").default(sql`(unixepoch())`).notNull(),
	updatedAt: integer("updated_at").default(sql`(unixepoch())`).notNull(),
});

